### ISSUE TITLE
:sparkles: Suppressing Calculations

### ISSUE THREAD

**Issue by rneswold** [DrMemCS/drmem#142]
Create a new variable, `{ignore}`, which is used to shut down a calculation path. If any subexpression evaluates to `{ignore}`, the expression returns `{ignore}`. If the `{ignore}` value propagates all the way to the top expression's result, the device isn't set. This variable is most useful for suppressing a conditional path. For instance, you might have a motion detector turn on a light, but also have a memory device that can disable the system:

```
{motion} -> {timer}

IFTE({enable_detection}, {timer}, {ignore}) -> {bulb}
```

**Comment by rneswold** [comment]
`!` is too hard to see and it shouldn't use the logic block's "variable" syntax. It should be a keyword; something that isn't too long but indicates no value will be provided.

`IGNORE`, `SKIP`, `STOP`, `SUPPRESS`, `BLOCK`, `NOTHING`?

**Comment by beauremus** [comment]
What about a system namespace to avoid collisions? `drmem:ignore`
I think the downside is that it's not succinct, but this can avoid thinking about this problem again.

**Comment by beauremus** [comment]
The way I said that made it sound like it was my idea, but I'm just agreeing with your brief suggestion of an "Internal variable".

Thinking about this more...
```
{drmem:motion} -> {drmem:timer}

IFTE({drmem:enable_detection}, {drmem:timer}, {drmem:ignore}) -> {drmem:bulb}
```
I don't know how typical your example is, but this pattern of repetition doesn't feel great.
Maybe some descretion is needed to determine what should be reserved words vs drmem namespace. Maybe the namespace could be shortened to `dm` or `cs`? Or maybe even more descriptive namespace_s_?

Is there a benefit to reserved words over "Internal variables"?

**Comment by rneswold** [comment]
I oversimplified how I described the expressions. A more realistic example would look like this (in `drmem.toml`):

```toml
[[logic]]
name = "Motion-Sensor"

inputs.motion = "backyard:floodlight:motion"
inputs.timer = "motion-timer:output"
inputs.enable_detection = "mem-device:enable-detection"

outputs.timer = "motion-timer:enable"
outputs.bulb = "backyard:light:state"

expressions = [
   "{motion} -> {timer}",
   "IFTE({enable_detection}, {timer}, {drmem:ignore}) -> {bulb}"
]
```

The `{}` syntax refers to names in the `inputs` and `outputs` maps. The values in these maps are the devices and the keys are names we use in the expressions to refer to the devices.

**Comment by rneswold** [comment]
> Is there a benefit to reserved words over "Internal variables"?

If I define a boolean memory device that I want an expression to use to conditionally handle a motion detector, I might call it `var:disable-motion-detecting`. I might set up a logic block that contains -- among other things -- this:

```toml
[[logic]]

inputs.ignore = "var:disable-motion-detecting"

expressions = [
    "IFTE(not {ignore} and {motion}, ..., ...) -> {bulb}"
]
```

We couldn't use `{ignore}` if we made it a special value case. But by making our "nothing" value represented with a reserved word, we wouldn't be claiming a name in the variable namespace.
